# Generated by Django 4.2.7 on 2026-03-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_discussion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdgroupmember',
            name='score',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
