# Generated by Django 4.2.7 on 2026-03-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_discussion', '0002_alter_gdgroupmember_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdgroupmember',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
