# Generated by Django 4.2.7 on 2026-02-24 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mi_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockInterviewPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='mock_interviews.mockinterviewsession')),
                ('student1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mi_pairs_as_s1', to='accounts.studentprofile')),
                ('student2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mi_pairs_as_s2', to='accounts.studentprofile')),
                ('student3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mi_pairs_as_s3', to='accounts.studentprofile')),
            ],
            options={
                'unique_together': {('session', 'student1', 'student2')},
            },
        ),
        migrations.CreateModel(
            name='MockInterviewEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication', models.DecimalField(decimal_places=1, max_digits=3)),
                ('confidence', models.DecimalField(decimal_places=1, max_digits=3)),
                ('technical', models.DecimalField(decimal_places=1, max_digits=3)),
                ('body_language', models.DecimalField(decimal_places=1, max_digits=3)),
                ('problem_solving', models.DecimalField(decimal_places=1, max_digits=3)),
                ('feedback', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('evaluatee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to='accounts.studentprofile')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to='accounts.studentprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='mock_interviews.mockinterviewsession')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('session', 'evaluator', 'evaluatee')},
            },
        ),
    ]
