# Generated by Django 4.2.7 on 2026-03-19 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_user_batch_remove_user_year'),
        ('core', '0012_alter_jobapplication_is_accepted_and_more'),
        ('mock_interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterviewsession',
            name='target_drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mi_sessions', to='core.placementdrive'),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='target_type',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('department', 'Specific Department'), ('drive', 'Specific Placement Drive')], default='everyone', max_length=20),
        ),
        migrations.AlterField(
            model_name='mockinterviewsession',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Filter students by department', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.course'),
        ),
        migrations.AlterField(
            model_name='mockinterviewsession',
            name='year',
            field=models.IntegerField(blank=True, help_text='Filter students by year', null=True),
        ),
    ]
