# Generated by Django 4.2.7 on 2026-02-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_studentprofile_backlogs_studentprofile_gender_and_more'),
        ('core', '0002_test_testattempt_question_mockinterview'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdrive',
            name='registration_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.RemoveField(
            model_name='placementdrive',
            name='eligible_departments',
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='min_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='eligible_departments',
            field=models.ManyToManyField(related_name='placement_drives', to='accounts.course'),
        ),
    ]
