# Generated by Django 4.2.7 on 2026-02-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_placementdrive_registration_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdrive',
            name='is_for_all_departments',
            field=models.BooleanField(default=False, help_text='If checked, all departments/courses are eligible'),
        ),
    ]
