# Generated by Django 4.2.7 on 2026-02-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_placementdrive_is_for_all_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdrive',
            name='category',
            field=models.CharField(choices=[('A', 'high'), ('B', 'medium'), ('C', 'low')], default='A'),
        ),
    ]
