# Generated by Django 4.2.7 on 2026-02-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_placementdrive_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementdrive',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
