# Generated by Django 4.2.7 on 2026-03-01 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_placementdrive_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target_type',
            field=models.CharField(choices=[('all', 'All Students'), ('drive', 'Specific Drive'), ('personal', 'Personal Message')], default='all', max_length=10),
        ),
    ]
