# Generated by Django 4.2.7 on 2026-03-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_announcement_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdrive',
            name='eligible_year',
            field=models.IntegerField(default=3, help_text='Eligible year of study (1, 2, 3, or 4)'),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='eligible_batch',
            field=models.IntegerField(help_text='Admission batch (e.g., 2022)'),
        ),
    ]
