# Generated by Django 4.2.7 on 2026-03-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_placementdrive_eligible_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_accepted',
            field=models.BooleanField(default=False, help_text='Ready to Work status'),
        ),
    ]
