# Generated by Django 4.2.7 on 2026-03-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_jobapplication_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='placed_at',
            field=models.DateTimeField(blank=True, help_text='Date coordinator marked this student as Placed', null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='is_accepted',
            field=models.BooleanField(default=False, help_text="Ready to Work: student's chosen final placement"),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='category',
            field=models.CharField(choices=[('A', 'Category A'), ('B', 'Category B'), ('C', 'Category C'), ('D', 'Category D')], default='A', max_length=2),
        ),
    ]
