# Generated by Django 4.2.7 on 2026-03-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_jobapplication_placed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='is_accepted',
            field=models.BooleanField(db_index=True, default=False, help_text="Ready to Work: student's chosen final placement"),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('placed', 'Placed')], db_index=True, default='applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='eligible_batch',
            field=models.IntegerField(db_index=True, help_text='Admission batch (e.g., 2022)'),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='eligible_year',
            field=models.IntegerField(db_index=True, default=3, help_text='Eligible year of study (1, 2, 3, or 4)'),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='registration_deadline',
            field=models.DateTimeField(db_index=True),
        ),
    ]
