# Generated by Django 4.2.7 on 2026-03-19 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0017_remove_user_batch_remove_user_year'),
        ('core', '0011_alter_jobapplication_is_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='is_accepted',
            field=models.BooleanField(default=False, help_text="Ready to Work: student's chosen final placement"),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('placed', 'Placed')], default='applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='eligible_batch',
            field=models.IntegerField(help_text='Admission batch (e.g., 2022)'),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='eligible_year',
            field=models.IntegerField(default=3, help_text='Eligible year of study (1, 2, 3, or 4)'),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='registration_deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('user', 'announcement')},
        ),
        migrations.AlterUniqueTogether(
            name='testattempt',
            unique_together={('student', 'test')},
        ),
    ]
