# Generated by Django 4.2.7 on 2026-04-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_jobapplication_is_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='eligible_batch',
            field=models.IntegerField(db_index=True, help_text='Admission batch (e.g., 2022)'),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='eligible_year',
            field=models.IntegerField(db_index=True, default=3, help_text='Eligible year of study (1, 2, 3, or 4)'),
        ),
    ]
