# Generated by Django 4.2.7 on 2026-04-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_notification_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='drive_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='eligible_batch',
            field=models.IntegerField(blank=True, help_text='Admission batch (e.g., 2022). Leave blank for All.', null=True),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='eligible_year',
            field=models.IntegerField(blank=True, default=0, help_text='Eligible year of study (1, 2, 3, or 4). Use 0 or Blank for All.', null=True),
        ),
    ]
