# Generated by Django 4.2.9 on 2026-02-04 15:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import resumes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_type', models.CharField(choices=[('uploaded', 'Uploaded Resume'), ('generated', 'AI Generated Resume')], default='uploaded', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to=resumes.models.upload_resume_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('skills', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('projects', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('ai_generated_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ATSScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('missing_skills', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('analysis_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_scores', to='resumes.resume')),
            ],
            options={
                'verbose_name': 'ATS Score',
                'verbose_name_plural': 'ATS Scores',
                'ordering': ['-created_at'],
            },
        ),
    ]
