# Generated by Django 4.2.7 on 2026-02-11 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atsscore',
            options={'ordering': ['-analyzed_at'], 'verbose_name': 'ATS Score', 'verbose_name_plural': 'ATS Scores'},
        ),
        migrations.RenameField(
            model_name='atsscore',
            old_name='created_at',
            new_name='analyzed_at',
        ),
        migrations.AddField(
            model_name='atsscore',
            name='action_verb_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atsscore',
            name='ai_adjustment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atsscore',
            name='ats_safety_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atsscore',
            name='experience_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atsscore',
            name='improvement_suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='atsscore',
            name='keyword_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atsscore',
            name='missing_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='atsscore',
            name='role_fit_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atsscore',
            name='skills_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atsscore',
            name='structure_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atsscore',
            name='target_role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='atsscore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='atsscore',
            name='weak_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='achievements_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_enhanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='certifications_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='education_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='languages_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='portfolio',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='projects_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='atsscore',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ats_score', to='resumes.resume'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL),
        ),
    ]
