# Generated by Django 4.2.7 on 2026-03-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_alter_atsscore_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atsscore',
            name='education_score',
            field=models.IntegerField(default=0),
        ),
    ]
