# Generated by Django 4.2.7 on 2026-03-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_atsscore_education_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atsscore',
            name='score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='atsscore',
            name='target_role',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
