# Generated by Django 4.2.7 on 2026-03-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_alter_atsscore_score_alter_atsscore_target_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atsscore',
            name='analysis_data',
        ),
        migrations.RemoveField(
            model_name='atsscore',
            name='missing_skills',
        ),
        migrations.RemoveField(
            model_name='atsscore',
            name='suggestions',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.AlterField(
            model_name='atsscore',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='atsscore',
            name='target_role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
