# Generated by Django 4.2.7 on 2026-04-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_remove_atsscore_analysis_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atsscore',
            name='analysis_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
