# Generated by Django 4.2.7 on 2026-02-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftest',
            name='is_published',
            field=models.BooleanField(default=True, help_text='If unchecked, students cannot see this test.'),
        ),
    ]
