# Generated by Django 4.2.7 on 2026-03-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude_test', '0002_pdftest_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdftest',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='If unchecked, students cannot see this test.'),
        ),
        migrations.AlterField(
            model_name='pdftestresult',
            name='score',
            field=models.IntegerField(db_index=True),
        ),
    ]
