# Generated by Django 4.2.7 on 2026-03-19 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_jobapplication_is_accepted_and_more'),
        ('accounts', '0017_remove_user_batch_remove_user_year'),
        ('aptitude_test', '0003_alter_pdftest_is_published_alter_pdftestresult_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftest',
            name='target_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_tests', to='accounts.course'),
        ),
        migrations.AddField(
            model_name='pdftest',
            name='target_drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_tests', to='core.placementdrive'),
        ),
        migrations.AddField(
            model_name='pdftest',
            name='target_type',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('department', 'Specific Department'), ('drive', 'Specific Placement Drive')], default='everyone', max_length=20),
        ),
        migrations.AlterField(
            model_name='pdftest',
            name='is_published',
            field=models.BooleanField(default=True, help_text='If unchecked, students cannot see this test.'),
        ),
        migrations.AlterField(
            model_name='pdftestresult',
            name='score',
            field=models.IntegerField(),
        ),
    ]
