# Generated by Django 4.2.7 on 2026-02-13 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_cgpa_studentprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)')], max_length=2)),
                ('type', models.CharField(help_text='e.g. Bachelor of Arts (B.A.), Master of Science (M.Sc.)', max_length=100)),
                ('name', models.CharField(help_text='e.g. Economics, Physics (Hons)', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.course'),
        ),
    ]
