# Generated by Django 4.2.7 on 2026-02-13 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_course_studentprofile_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='department',
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, db_column='department', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.course'),
        ),
    ]
