# Generated by Django 4.2.7 on 2026-03-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_studentprofile_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='batch',
            field=models.IntegerField(blank=True, help_text='Admission Year (YYYY)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='batch',
            field=models.IntegerField(blank=True, help_text='Admission Year (YYYY)', null=True),
        ),
    ]
