# Generated by Django 4.2.7 on 2026-03-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_studentprofile_batch_user_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='batch',
            field=models.IntegerField(blank=True, help_text='Admission Year (YYYY)', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default=1),
        ),
    ]
