# Generated by Django 4.2.7 on 2026-03-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_course_batch_course_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='batch',
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default=3, help_text='Course duration in years'),
        ),
    ]
