# Generated by Django 4.2.7 on 2026-03-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_course_batch_alter_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year'), (6, '6th Year'), (7, '7th Year'), (8, '8th Year'), (9, '9th Year'), (10, '10th Year')], default=3, help_text='Course duration in years'),
        ),
    ]
