# Generated by Django 4.2.7 on 2026-03-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default=3, help_text='Course duration in years'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='batch',
            field=models.IntegerField(blank=True, db_index=True, help_text='Admission Year (YYYY)', null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='placement_status',
            field=models.CharField(choices=[('not_placed', 'Not Placed'), ('placed', 'Placed')], db_index=True, default='not_placed', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
    ]
