# Generated by Django 4.2.7 on 2026-03-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_course_year_alter_studentprofile_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='batch',
            field=models.IntegerField(blank=True, help_text='Admission Year (YYYY)', null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='placement_status',
            field=models.CharField(choices=[('not_placed', 'Not Placed'), ('placed', 'Placed')], default='not_placed', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year',
            field=models.IntegerField(),
        ),
    ]
