# Generated by Django 4.2.7 on 2026-03-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_drop_otp_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='year',
        ),
    ]
