# Generated by Django 4.2.7 on 2026-04-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_user_batch_remove_user_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='batch',
            field=models.IntegerField(blank=True, db_index=True, help_text='Admission Year (YYYY)', null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('coordinator', 'Coordinator'), ('admin', 'Admin')], db_index=True, default='admin', max_length=20),
        ),
    ]
