# Generated by Django 4.2.7 on 2026-06-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_studentprofile_batch_alter_studentprofile_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='batch',
            field=models.IntegerField(blank=True, help_text='Admission Year (YYYY)', null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('coordinator', 'Coordinator'), ('admin', 'Admin')], default='admin', max_length=20),
        ),
    ]
