# Generated by Django 4.2.7 on 2026-03-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='physicalsession',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
