# Generated by Django 4.2.7 on 2026-03-19 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_jobapplication_is_accepted_and_more'),
        ('accounts', '0017_remove_user_batch_remove_user_year'),
        ('attendance', '0003_alter_attendance_is_present_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalsession',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='accounts.course'),
        ),
        migrations.AddField(
            model_name='physicalsession',
            name='target_drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='core.placementdrive'),
        ),
        migrations.AddField(
            model_name='physicalsession',
            name='target_type',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('department', 'Specific Department'), ('drive', 'Specific Placement Drive')], default='everyone', max_length=20),
        ),
    ]
